application: smzdm-for-linhaoran
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /test
  script: FetchRSS2.app
- url: /test2
  script: FetchRSS2.app

- url: /notify
  script: smzdm.app
- url: /smzdm
  script: smzdm.app
- url: /keywords
  script: smzdm.app

- url: /hello2
  script: helloworld2.app

- url: /.*
  script: helloworld.app

